[package]
name = "benches"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "4.0.0"
wasmtime-wasi = "4.0.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "instantiation"
harness = false
